name: ${ENV_CONTAINER_NAME}

services:
  python-jupyter:
    pull_policy: build
    build:
      context: .
      args:
        - PYTHON_VERSION=${ENV_PYTHON_VERSION}
        - JUPYTERLAB_VERSION=${ENV_JUPYTERLAB_VERSION}
        - UID=1000
        - GID=1000
    image: python-jupyter-venv:py${ENV_PYTHON_VERSION}-jl${ENV_JUPYTERLAB_VERSION}
    container_name: ${ENV_CONTAINER_NAME}
    restart: "no"
    environment:
      - ENV_PYTHON_VERSION=${ENV_PYTHON_VERSION}
      - ENV_JUPYTERLAB_VERSION=${ENV_JUPYTERLAB_VERSION}
    ports:
      - 7512:8888
    volumes:
      - ./:/home/pyuser/workspace:Z
    networks:
      - python_jupyter_net

networks:
  python_jupyter_net:
    name: python_jupyter_net
